### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by maxogden** [Runscope/requestbin#17]
it would be nice if requestbin had CORS headers enabled so I could use it for testing client side HTTP

**Comment by nodesocket** [comment]
Is CORS still not supported with POST requests? I am getting:

> XMLHttpRequest cannot load http://requestb.in/1i8ys0s1. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access.

**Comment by lenichols** [comment]
Same here... @nodesocket im getting CORS error too

**Comment by diogoca** [comment]
same here...

**Comment by swrobel** [comment]
You guys fixed this on [HTTPbin](https://github.com/Runscope/httpbin), don't get why it can't be fixed here...

**Comment by MatissJanis** [comment]
Still getting a CORS error.

**Comment by GabLeRoux** [comment]
I sent a PR (that I don't really expect to be merged) as it may not be secure or at least it would need some cleanup. At least if it can help someone, you can grab it and install it on heroku :)

https://github.com/GabLeRoux/requestbin/tree/wide-open-cors-with-allow-header-fix

**Comment by GabLeRoux** [comment]
This issue can be closed in favor of #34
Instructions in previous comment 🎉

**Comment by whitneyland** [comment]
Seems to be fixed technically.  However some feedback for what its worth: There's still too much friction and rough edges to using it that could discourage new developers from runscope.

For example, I imagine the typical experience goes something like this, where the developer:

1. Needs to see endpoint results of making an api call, the api may not even exist yet
2. Finds requestbin via google, tries a GET example, works in 60 seconds, awesome!  I love this!
3. Tries a POST example, fails because of requestbin CORS support
4. Googles this git issue, realizes it's intentional, works only if you signup with runscope.  some of the excitement fizzles, but hey, starting a company is tough so we understand.  signup and continue.
5. Before signup took 60 seconds to get requestbin working, after signup you are clueless and start wondering around a mishmash of tutorials, runscope specific terms and jargon, and incomplete documentation.

What happened?

- Searching docs and help on runscope.com for CORS gives no useful results.  How is that even possible, knowing people are funneling to requestbin, then here, then signingup for runscope?
- Developer first experience workflow has not been well tested. It's not lack of effort, clearly lots of effort has gone into tutorials, docs, step by step instructions. It's just that no UX test/optimize/iterate loop with with devs new to the service is being maintained.

**Comment by johnsheehan** [comment]
CORS only needs to be enabled for requests made to requestbin from client-side JS. Most people use RequestBin to inspect requests from 3rd-party webhooks providers or server-side code, which doesn’t require CORS. I linked to the specific doc for the feature you need in Runscope to inspect CORS requests. Sorry you were confused.
